### ISSUE TITLE
Reminder alert and whois update schedule

### ISSUE THREAD

**Issue by aptalca** [nwesterhausen/domain-monitor#41]
**Describe the bug**
1. Based on the wording in the readme, specifically the part `and to help remind you when they need renewed` in the first sentence led me to believe there would me email reminders when we got closer to the registration expiration. We are now within 60 days of expiration for one of my domains, and I have not received an email. I was wondering if there are really reminder emails and if so what the schedule for those would be.

2. I also noticed that the whois query time is listed as `2022-04-05` for that domain. However, the readme suggests the whois reference would be updated if one of the listed conditions are met, and one of those conditions is `It's 3 months until the domain expiry date`. That does not seem to have happened here as we are 60 days from expiration, but the last query date is many months ago.

**To Reproduce**
1. Create a docker container as described in the readme (from ghcr)
2. Populate the yaml config and confirm the info in the webgui for various domains
3. Wait until close to expiration on one of the domains

**Expected behavior**
1. Whois query would be updated 3 months prior to expiration
2. Expiration reminder email would be sent (at some point I'm not sure)

**Screenshots**
![Screenshot 2023-03-05 203628](https://user-images.githubusercontent.com/541623/223000605-243cf15c-81af-45a7-be00-4ff189f152de.png)

**Desktop (please complete the following information):**
 - OS: Unraid/Docker
 - Browser: Chrome
 - Version: 110

**Smartphone (please complete the following information):**
N/A

**Additional context**
I set the container up some months ago and it seems to be working and I see the info in the webgui for a number of domains. However, there was no `test email` function so I was not able to confirm whether email alerts were set up properly or working.

Thanks

**Comment by aptalca** [comment]
Since my original post, I went ahead and renewed the domain registration that was to expire within 60 days. Upon a restart the app did a new whois check and recognized the updated expiration date. However, there was no alert generated. No mention of an alert in the logs either.

**Comment by nwesterhausen** [comment]
Hello.

Looking through the code, it looks like I set up the mailer and an alert function, but the send alert function is never called. I've gone back and looked to when it was added and never got actually connected. The readme and settings imply that email alerts will get sent, and that's because it was a planned feature before I took a break from this project.

I will make best effort to apply some updates to this project, especially adding in a `send test alert` to test the mailer and the logic to dictate the alerts.

The changes to the code to connect the alerts up properly require:

- adding a timer or scheduler to look at the WHOIS expirations
- measure the time between current time and expiration date
- compare the difference to the constraints (I suppose we could use the WHOIS update periods as triggers, 3 months, 2 months, 1 month)
- send an alert
- also we have to track what events we sent an alert for and remember so we don't keep alerting every WHOIS expiration examination
