### ISSUE TITLE
Privacy issues

### ISSUE THREAD

**Issue by hashimaziz1** [nwesterhausen/domain-monitor#70]
Hi Nicholas, thanks a lot for this great tool, I've been looking for something like it for a long time. 

I just have a few questions that I'd love to get clarification on. 

Firstly, is there any issue with the tool being used to monitor domains that you don't yet own? Is any verification needed from the domain owner for a domain to be monitored?

Secondly, do you or DomainMonitor have any awareness of the domains being monitored? Or put another way, does the tool ever call back to any servers other than the WHOIS APIs needed for the lookups? I've had a quick scan through the source and can't find anything that would, but just wanted to get an assurance of this. If this is not currently the case, will it ever change? 

Thanks in advance and thanks again for your work on this, it's much appreciated.

**Comment by nwesterhausen** [comment]
Hello! Sorry for the late reply..

No, there is no tracking/call back to me or anyone about what you are monitoring. I have no intention of ever doing that.

Regarding which domains you track, since the WHOIS system lets you query any domain arbitrarily there are also no restrictions using Domain Monitor. The WHOIS system is public by design, and when I started this project the only kind of restrictions I ever saw posted were just to limit the number of queries and be a good API user. Domain Monitor does this by caching the responses it gets and only re-querying often close to the domain expiration date.
